import type { Match } from "@/types/match"
import { buildMatch } from "./helpers"

export function bundesligaMatches(): Match[] {
  return [
    buildMatch({
      league: "Bundesliga",
      country: "Germany",
      venue: "Allianz Arena",
      homeName: "Bayern Munich",
      homeShort: "BAY",
      awayName: "Borussia Dortmund",
      awayShort: "BVB",
      kickoffMinutes: 60,
      baseOdds: { home: 1.75, draw: 4.0, away: 4.2 },
      homeForm: "WWWWW",
      awayForm: "WDWLW",
      confidence: 84,
      advice: "Bayern Win",
    }),
    buildMatch({
      league: "Bundesliga",
      country: "Germany",
      venue: "Red Bull Arena",
      homeName: "RB Leipzig",
      homeShort: "RBL",
      awayName: "Bayer Leverkusen",
      awayShort: "B04",
      kickoffMinutes: -55,
      status: "LIVE",
      minute: 73,
      score: { home: 1, away: 2 },
      baseOdds: { home: 2.6, draw: 3.4, away: 2.55 },
      homeForm: "WDLWW",
      awayForm: "WWWWD",
      confidence: 76,
      advice: "Leverkusen Win",
      events: [
        { minute: 18, team: "away", type: "goal", player: "Wirtz", detail: "Right foot" },
        { minute: 49, team: "home", type: "goal", player: "Openda", detail: "Left foot" },
        { minute: 67, team: "away", type: "goal", player: "Boniface", detail: "Header" },
      ],
    }),
    buildMatch({
      league: "Bundesliga",
      country: "Germany",
      venue: "Deutsche Bank Park",
      homeName: "Eintracht Frankfurt",
      homeShort: "SGE",
      awayName: "Wolfsburg",
      awayShort: "WOB",
      kickoffMinutes: 25 * 60,
      baseOdds: { home: 2.0, draw: 3.6, away: 3.8 },
      homeForm: "WLWWD",
      awayForm: "DLDLW",
      confidence: 68,
      advice: "Frankfurt Win",
    }),
    buildMatch({
      league: "Bundesliga",
      country: "Germany",
      venue: "Veltins-Arena",
      homeName: "Schalke 04",
      homeShort: "S04",
      awayName: "Stuttgart",
      awayShort: "VFB",
      kickoffMinutes: 49 * 60,
      baseOdds: { home: 3.4, draw: 3.3, away: 2.1 },
      homeForm: "LDLDL",
      awayForm: "WWDWW",
      confidence: 72,
      advice: "Stuttgart Win",
    }),
  ]
}
