import type { Match } from "@/types/match"
import { buildMatch } from "./helpers"

export function laLigaMatches(): Match[] {
  return [
    buildMatch({
      league: "La Liga",
      country: "Spain",
      venue: "Spotify Camp Nou",
      homeName: "Barcelona",
      homeShort: "BAR",
      awayName: "Real Madrid",
      awayShort: "RMA",
      kickoffMinutes: 90,
      baseOdds: { home: 2.55, draw: 3.4, away: 2.6 },
      homeForm: "WWDWW",
      awayForm: "WWWWD",
      confidence: 82,
      advice: "Over 2.5 Goals",
    }),
    buildMatch({
      league: "La Liga",
      country: "Spain",
      venue: "Cívitas Metropolitano",
      homeName: "Atlético Madrid",
      homeShort: "ATM",
      awayName: "Sevilla",
      awayShort: "SEV",
      kickoffMinutes: -25,
      status: "LIVE",
      minute: 38,
      score: { home: 1, away: 0 },
      baseOdds: { home: 1.75, draw: 3.6, away: 4.5 },
      homeForm: "WDWWL",
      awayForm: "LDLWD",
      confidence: 75,
      advice: "Atlético Win",
      events: [{ minute: 21, team: "home", type: "goal", player: "Griezmann", detail: "Right foot" }],
      stats: {
        possession: { h: 58, a: 42 },
        shots: { h: 8, a: 3 },
        shotsOnTarget: { h: 4, a: 1 },
        xg: { h: 1.4, a: 0.3 },
        passAccuracy: { h: 86, a: 78 },
        corners: { h: 4, a: 1 },
      },
    }),
    buildMatch({
      league: "La Liga",
      country: "Spain",
      venue: "Estadio de Mestalla",
      homeName: "Valencia",
      homeShort: "VAL",
      awayName: "Real Sociedad",
      awayShort: "RSO",
      kickoffMinutes: 22 * 60,
      baseOdds: { home: 2.8, draw: 3.2, away: 2.5 },
      homeForm: "DDWLL",
      awayForm: "WLWDD",
      confidence: 56,
      advice: "Draw No Bet — Sociedad",
    }),
    buildMatch({
      league: "La Liga",
      country: "Spain",
      venue: "Benito Villamarín",
      homeName: "Real Betis",
      homeShort: "BET",
      awayName: "Villarreal",
      awayShort: "VIL",
      kickoffMinutes: 25 * 60,
      baseOdds: { home: 2.4, draw: 3.3, away: 2.85 },
      homeForm: "WWLDW",
      awayForm: "DWLDW",
      confidence: 67,
      advice: "Both Teams to Score",
    }),
    buildMatch({
      league: "La Liga",
      country: "Spain",
      venue: "RCDE Stadium",
      homeName: "Espanyol",
      homeShort: "ESP",
      awayName: "Getafe",
      awayShort: "GET",
      kickoffMinutes: 48 * 60,
      baseOdds: { home: 2.6, draw: 3.0, away: 2.95 },
      homeForm: "LDDWL",
      awayForm: "DDLWL",
      confidence: 48,
      advice: "Under 2.5 Goals",
    }),
  ]
}
