import type { Match } from "@/types/match"
import { buildMatch } from "./helpers"

export function ligue1Matches(): Match[] {
  return [
    buildMatch({
      league: "Ligue 1",
      country: "France",
      venue: "Parc des Princes",
      homeName: "Paris Saint-Germain",
      homeShort: "PSG",
      awayName: "Marseille",
      awayShort: "MAR",
      kickoffMinutes: 90,
      baseOdds: { home: 1.55, draw: 4.5, away: 5.5 },
      homeForm: "WWWWW",
      awayForm: "DLWDW",
      confidence: 88,
      advice: "PSG Win",
    }),
    buildMatch({
      league: "Ligue 1",
      country: "France",
      venue: "Groupama Stadium",
      homeName: "Lyon",
      homeShort: "OL",
      awayName: "Monaco",
      awayShort: "MON",
      kickoffMinutes: -15,
      status: "LIVE",
      minute: 27,
      score: { home: 0, away: 1 },
      baseOdds: { home: 2.85, draw: 3.4, away: 2.45 },
      homeForm: "WLWDD",
      awayForm: "WWLWW",
      confidence: 69,
      advice: "Monaco Win",
      events: [{ minute: 14, team: "away", type: "goal", player: "Embolo", detail: "Header" }],
    }),
    buildMatch({
      league: "Ligue 1",
      country: "France",
      venue: "Allianz Riviera",
      homeName: "Nice",
      homeShort: "NCE",
      awayName: "Lille",
      awayShort: "LIL",
      kickoffMinutes: 22 * 60,
      baseOdds: { home: 2.5, draw: 3.1, away: 2.95 },
      homeForm: "WDWWL",
      awayForm: "DWLDW",
      confidence: 61,
      advice: "Both Teams to Score",
    }),
    buildMatch({
      league: "Ligue 1",
      country: "France",
      venue: "Stade Pierre-Mauroy",
      homeName: "Rennes",
      homeShort: "REN",
      awayName: "Strasbourg",
      awayShort: "STR",
      kickoffMinutes: 47 * 60,
      baseOdds: { home: 2.1, draw: 3.4, away: 3.5 },
      homeForm: "DWLWD",
      awayForm: "DDLWL",
      confidence: 59,
      advice: "Rennes Win",
    }),
  ]
}
