import type { Match } from "@/types/match"
import { buildMatch } from "./helpers"

export function premierLeagueMatches(): Match[] {
  return [
    buildMatch({
      league: "Premier League",
      country: "England",
      venue: "Emirates Stadium",
      homeName: "Arsenal",
      homeShort: "ARS",
      awayName: "Manchester City",
      awayShort: "MCI",
      kickoffMinutes: -45,
      status: "LIVE",
      minute: 67,
      score: { home: 2, away: 1 },
      baseOdds: { home: 2.45, draw: 3.2, away: 2.8 },
      homeForm: "WWWDW",
      awayForm: "WLWWD",
      confidence: 78,
      advice: "Arsenal Win",
      events: [
        { minute: 12, team: "home", type: "goal", player: "Saka", detail: "Right foot" },
        { minute: 34, team: "away", type: "goal", player: "Haaland", detail: "Header" },
        { minute: 58, team: "home", type: "goal", player: "Ødegaard", detail: "Penalty" },
        { minute: 41, team: "away", type: "card", player: "Rodri", detail: "Yellow" },
      ],
      stats: {
        possession: { h: 48, a: 52 },
        shots: { h: 11, a: 9 },
        shotsOnTarget: { h: 5, a: 3 },
        xg: { h: 1.8, a: 1.2 },
        passAccuracy: { h: 84, a: 88 },
        corners: { h: 5, a: 4 },
      },
    }),
    buildMatch({
      league: "Premier League",
      country: "England",
      venue: "Old Trafford",
      homeName: "Manchester United",
      homeShort: "MUN",
      awayName: "Liverpool",
      awayShort: "LIV",
      kickoffMinutes: 45,
      baseOdds: { home: 3.1, draw: 3.4, away: 2.25 },
      homeForm: "DLWLW",
      awayForm: "WWDWW",
      confidence: 71,
      advice: "Liverpool to Win",
    }),
    buildMatch({
      league: "Premier League",
      country: "England",
      venue: "Stamford Bridge",
      homeName: "Chelsea",
      homeShort: "CHE",
      awayName: "Tottenham",
      awayShort: "TOT",
      kickoffMinutes: 120,
      baseOdds: { home: 2.1, draw: 3.5, away: 3.4 },
      homeForm: "WWLDW",
      awayForm: "DWLLW",
      confidence: 64,
      advice: "Both Teams to Score",
    }),
    buildMatch({
      league: "Premier League",
      country: "England",
      venue: "Goodison Park",
      homeName: "Everton",
      homeShort: "EVE",
      awayName: "Newcastle",
      awayShort: "NEW",
      kickoffMinutes: 24 * 60,
      baseOdds: { home: 3.6, draw: 3.3, away: 2.05 },
      homeForm: "LDLLW",
      awayForm: "WDWWL",
      confidence: 58,
      advice: "Newcastle Win or Draw",
    }),
    buildMatch({
      league: "Premier League",
      country: "England",
      venue: "Villa Park",
      homeName: "Aston Villa",
      homeShort: "AVL",
      awayName: "Brighton",
      awayShort: "BHA",
      kickoffMinutes: 26 * 60,
      baseOdds: { home: 1.95, draw: 3.6, away: 3.8 },
      homeForm: "WWWDD",
      awayForm: "DLWDL",
      confidence: 73,
      advice: "Aston Villa Win",
    }),
    buildMatch({
      league: "Premier League",
      country: "England",
      venue: "London Stadium",
      homeName: "West Ham",
      homeShort: "WHU",
      awayName: "Crystal Palace",
      awayShort: "CRY",
      kickoffMinutes: -200,
      status: "FINISHED",
      score: { home: 1, away: 2 },
      baseOdds: { home: 2.3, draw: 3.3, away: 3.0 },
      homeForm: "DLWLD",
      awayForm: "WLWWD",
      confidence: 62,
      advice: "Palace Upset",
      events: [
        { minute: 23, team: "away", type: "goal", player: "Mateta", detail: "Left foot" },
        { minute: 56, team: "home", type: "goal", player: "Bowen", detail: "Right foot" },
        { minute: 88, team: "away", type: "goal", player: "Eze", detail: "Free kick" },
      ],
    }),
  ]
}
