import type { Match } from "@/types/match"
import { buildMatch } from "./helpers"

export function serieAMatches(): Match[] {
  return [
    buildMatch({
      league: "Serie A",
      country: "Italy",
      venue: "San Siro",
      homeName: "Inter Milan",
      homeShort: "INT",
      awayName: "Juventus",
      awayShort: "JUV",
      kickoffMinutes: 75,
      baseOdds: { home: 2.0, draw: 3.4, away: 3.6 },
      homeForm: "WWDWW",
      awayForm: "WDWWL",
      confidence: 79,
      advice: "Inter Win",
    }),
    buildMatch({
      league: "Serie A",
      country: "Italy",
      venue: "Stadio Olimpico",
      homeName: "Roma",
      homeShort: "ROM",
      awayName: "Lazio",
      awayShort: "LAZ",
      kickoffMinutes: -10,
      status: "LIVE",
      minute: 12,
      score: { home: 0, away: 0 },
      baseOdds: { home: 2.3, draw: 3.2, away: 3.1 },
      homeForm: "WDWLD",
      awayForm: "DWLWD",
      confidence: 60,
      advice: "Both Teams to Score",
      stats: {
        possession: { h: 52, a: 48 },
        shots: { h: 2, a: 1 },
        shotsOnTarget: { h: 1, a: 0 },
        xg: { h: 0.2, a: 0.1 },
        passAccuracy: { h: 81, a: 79 },
        corners: { h: 1, a: 0 },
      },
    }),
    buildMatch({
      league: "Serie A",
      country: "Italy",
      venue: "Stadio Diego Armando Maradona",
      homeName: "Napoli",
      homeShort: "NAP",
      awayName: "AC Milan",
      awayShort: "MIL",
      kickoffMinutes: 23 * 60,
      baseOdds: { home: 2.4, draw: 3.3, away: 2.85 },
      homeForm: "WWLDW",
      awayForm: "DWLWW",
      confidence: 70,
      advice: "Napoli or Draw",
    }),
    buildMatch({
      league: "Serie A",
      country: "Italy",
      venue: "Artemio Franchi",
      homeName: "Fiorentina",
      homeShort: "FIO",
      awayName: "Atalanta",
      awayShort: "ATA",
      kickoffMinutes: 27 * 60,
      baseOdds: { home: 2.9, draw: 3.4, away: 2.4 },
      homeForm: "DLWDW",
      awayForm: "WWDWL",
      confidence: 65,
      advice: "Atalanta Win",
    }),
    buildMatch({
      league: "Serie A",
      country: "Italy",
      venue: "Stadio Olimpico Grande Torino",
      homeName: "Torino",
      homeShort: "TOR",
      awayName: "Bologna",
      awayShort: "BOL",
      kickoffMinutes: 50 * 60,
      baseOdds: { home: 2.65, draw: 3.0, away: 2.85 },
      homeForm: "DDLWL",
      awayForm: "WDDDW",
      confidence: 53,
      advice: "Draw",
    }),
  ]
}
